context:
  version: 1.3.0

package:
  name: sbck
  version: '{{ version }}'

source:
  # path: .
  - git_url: https://github.com/yrobink/SBCK-python.git
    git_rev: 'v{{ version }}'
    # git_rev: master
    git_depth: 1

build:
  # noarch: python
  number: 0
  script: python -m pip install --ignore-installed .
  include_recipe: false

requirements:

  # build:
  #   - python
  #   - setuptools
  #   - "{{ compiler('cxx') }}"
  #   - pybind11 >=2.2
  #   - eigen >=3.4.0
  #   # - sel(linux): gxx
  #   # - sel(osx): clangxx
  #   # - python
  #   # - setuptools
  #   # - sel(linux): "{{ compiler('cxx') }}"
  #   # - sel(osx): "{{ compiler('clang') }}"
  #   # - "{{ compiler('c') }}"
  #   # - gxx >=13.1.0
  #   # - pybind11 >=2.2
  #   # - eigen >=3.4.0

  host:
    - python
    - setuptools
    - pybind11 >=2.2
    - eigen >=3.4.0
  #   # - setuptools
  #   # - "{{ compiler('cxx') }}"
  #   # - sel(linux): gxx
  #   # - sel(osx): clangxx
  #   # - "{{ compiler('c++') }}"
  #   # # - gxx >=13.1.0

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pybind11 >=2.2
    - pot >=0.9.0

test:
  imports:
    - SBCK
